name: Android

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: yarn install

      - run: cd android && ./gradlew assembleRelease && cd ..
        name: Build Android apk (release)

      - name: Releasing using Hub
        uses: js1233/CiCdTestingApp@main
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          APP_FOLDER: app
