name: iOS OS
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: yarn install && cd ios && pod install
        name: Build ipa for distribution
      - run: cd ios && pod install &&  xcodebuild -project CiCdTestingApp.xcodeproj -scheme "CiCdTestingApp" -archivePath out/CiCdTestingApp.xcarchive archive
