name: iOS OS
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode.app
      - name: Xcode version
        run: /usr/bin/xcodebuild -version
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          APPLE_PROFILE: ${{ secrets.APPLE_PROFILE }}
          APPLE_CERT: ${{ secrets.APPLE_CERT }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID}}
      - name: Build archive
        run: cd ios && yarn install && pod install && xcodebuild archive -workspace ./CiCdTestingApp.xcworkspace -scheme CiCdTestingApp -destination 'generic/platform=iOS' -archivePath ../builds/CiCdTestingApp.xcarchive -allowProvisioningUpdates
      - name: Export Archive
        run: cd ios && yarn install && pod install && xcodebuild -exportArchive -archivePath ../builds/CiCdTestingApp.xcarchive -exportOptionsPlist ./exportOptions.plist -exportPath ../builds
###...
